### ISSUE TITLE
movie features availability?

### ISSUE THREAD

**Issue by jsmentch** [catcamacho/hbn_analysis#1]
Hello, very cool paper! Would you be able to share the movie features, particularly these great emotion features?

**Comment by catcamacho** [comment]
Yep, we have them publicly available here: https://wustl.app.box.com/v/emocodespublicdata/folder/165162908841

More info can be found at https://emocodes.org/

**Comment by catcamacho** [comment]
Added the link to the readme!

**Comment by jsmentch** [comment]
Awesome, thank you!
